### ISSUE TITLE
Custom URL in  SD_Switch_Model not work

### ISSUE THREAD

**Issue by duhanov** [stassius/StableHoudini#12]
I enable "Use custom URL" In SD_Switch_Model, but this now working. I enable in ARGS --api-log and --api,  but not see requests to Automatic from Houdini.

If im test api via CURL - all good! I'm see requests in automatic.

Please, help me

**Comment by stassius** [comment]
Thank you for report! I found the error on SD Switch Model. Please pull the last commit, it should be fixed. Let me know if the problem persists.

**Comment by duhanov** [comment]
Im run git pull, create new project and reinstall assets... But, not work...

**Comment by stassius** [comment]
Just to clarify, Git pull could not work if you changed any files. Did you pull it successfully? Check the creation time on the top_stable_diffusion.hda or you can download it manually and replace the file.
SD Switch model should work with custom URL now, at least in my tests.
Also, check if Houdini is not blocked in a firewall.

**Comment by duhanov** [comment]
In Python Shell Window (Houdini) im see ((: 

Connection error: http://xxx.xxx.xxx.xxx:7860/sdapi/v1/sd-models

**Comment by stassius** [comment]
Did you check if the hda-file was actually updated? Did you check the firewall rules?
I don't have a server to test it, but I spoofed URL through the hosts-file an everything works fine to me.

**Comment by duhanov** [comment]
Im remove folder and clone git again.Firewall not enabled... 

 Im see: Houdini can't connect to remote host  But... why...? Can i write you direct, and test my server?

**Comment by duhanov** [comment]
If i change via hosts file my host-address to localhost - work with local Server - ok. But, remote - fail

**Comment by stassius** [comment]
Write me in telegram, @stanislav_de

**Comment by stassius** [comment]
Tested on our end, error is on the client side. Closing the issue.
