### ISSUE TITLE
Why I need to reinstall asset StableHoudini every time I restart the Houdini 19.5?

### ISSUE THREAD

**Issue by supwang** [stassius/StableHoudini#14]
Hi,
I have some questions.
1. Why I need to reinstall asset StableHoudini every time I restart the Houdini 19.5?
2. How to use VAE?
3. How to know the number of current task? I filled @pdg_index... in Normalized time for ramgs and updated prompts to  (cat:#0) or (dog:#!0). After Cooked, the prompts in SD_Prompt are still cat:0.5 and dog:1.5?
Thank you.

**Comment by stassius** [comment]
Hello! Please, if you have questions, ask them in Discussions tab. Issues are only for bugs or improvements.
1. If you want the assets to be loaded in a project on Houdini start up, create a system environment variable called HOUDINI_OTLSCAN_PATH and put the path to the assets folder there.

2. There is no way of getting the list of installed VAEs through API. But if you know the exact name of your VAE, you can set it with the SD Set Option node like this:
![image](https://user-images.githubusercontent.com/35260274/235607768-6e926d6f-a058-41e7-b55e-2eda8c12fa4a.png)

But please, update the toolset, as I fixed some bugs in this node in the last commit.

3. If you have a cooked node (it has green circles), then don't just Cook it, but choose Dirty and cook this node.
