### ISSUE TITLE
Connection error

### ISSUE THREAD

**Issue by Limbicnation** [stassius/StableHoudini#17]
I am getting a connection error when using a custom URL to launch the 1111 webui.

<img width="474" alt="image" src="https://user-images.githubusercontent.com/6284675/235735869-69034fe4-97bb-4765-9c7a-115ca595128c.png">

<img width="548" alt="image" src="https://user-images.githubusercontent.com/6284675/235734608-32d082e3-b45f-460f-8a28-b3fb71b87f1b.png">

The process is stuck here:
`LatentDiffusion: Running in eps-prediction mode
DiffusionWrapper has 859.53 M params.
Applying cross attention optimization (Doggettx).
Model loaded in 2.1s (create model: 0.2s, apply weights to model: 0.6s, apply half(): 0.4s, move model to device: 0.9s).`

**Comment by stassius** [comment]
It looks like a connection error from another node. You should switch Use custom URL parameter on every SD node in the network. You can tie these parameters together. I'm planning to make the URL usage easier in the near future.

**Comment by Limbicnation** [comment]
Thank you, this worked. I was running another node with the same URL.

<img width="864" alt="image" src="https://user-images.githubusercontent.com/6284675/235741714-b976c315-afac-48b5-a35d-df0671666ad8.png">
