### ISSUE TITLE
controlnet api endpoints deprecation

### ISSUE THREAD

**Issue by mrmcdobrotny** [stassius/StableHoudini#2]
`/controlnet/model_list` and `/controlnet/module_list` are not available anymore, and I can't find the exact commit of control net repo that will work with it. 
is there any other wat to fetch those data? I'm searching api docs for replacement to this, but still have no luck 
also when I hardcode preprocessor name and model the control net does not seem to have any effect even if its enabled in ui

**Comment by stassius** [comment]
I'll check it out. The current ControlNet commit that works on my end is 3696298

**Comment by stassius** [comment]
Well, I don't know what's the issue. I just pulled the last ControlNet commit and everything is in place, both endpoints are working.

**Comment by mrmcdobrotny** [comment]
pulling both repos fixed my issue
current commits are [93b0f9e](https://github.com/Mikubill/sd-webui-controlnet/tree/93b0f9e1b7cc246165666b7b307bc8243db2c3f4) for control net
and [22bcc7b](https://github.com/AUTOMATIC1111/stable-diffusion-webui/tree/22bcc7be428c94e9408f589966c2040187245d81) for webui
