### ISSUE TITLE
[BUG]

### ISSUE THREAD

**Issue by JasonSongPeng** [stassius/StableHoudini#22]
When I apply controlnet in the mode of Text2image,
I got a error:  Error: No upstream images for ControlNet 0

![image](https://user-images.githubusercontent.com/57006745/236473275-9da8cd59-b41d-4bde-92b5-9d601d822cf6.png)

How can I link my viewport to controlNet?

Thank you so much!

**Comment by stassius** [comment]
Upstream image is an image stored in File attribute in the previous nodes. For example you can get one by reading files with File Pattern node, by rendering image with Rop fetch node or by generating an image with SD Dream node.
In my last tutorial I explained how to get a depth map from your viewport.
https://www.youtube.com/watch?v=SJ5o18kJkRA

**Comment by stassius** [comment]
I assume this is not a bug. If you have questions, please post them in QnA section of the Discussion tab. Feel free to open a new bug report if you got problems.
