### ISSUE TITLE
404

### ISSUE THREAD

**Issue by aerovfx** [stassius/StableHoudini#23]
**Describe the bug**

When I installed Asset HDA, added Topnet, and then added the node SD_Switch_Model1, the console displayed the message:
 "Error retrieving list: models"
and "Server returned: 404".
![ssssssssssssss](https://user-images.githubusercontent.com/109997053/236506319-230ba1f7-c2ae-4e42-aeb2-ea16c1b0679d.PNG)

Why am I getting an error of incorrect model path?

**Comment by stassius** [comment]
1. Check if you added --api key to your webui-user.bat.
2. Make sure to start A1111 with webui-user.bat
3. Check if Houdini is not blocked in your firewall
4. Check the url and the port, as they can vary depending on existing web-services on your computer

**Comment by aerovfx** [comment]
![ssssssssssssssssssssssssssssss](https://user-images.githubusercontent.com/109997053/236508488-917eef1e-f4c6-4c66-83e8-9af45e88c0a2.PNG)
I ran the application on port 7860 and followed the instructions, including the config file, and restarted Houdini.
One strange thing is that the application ran successfully on the first attempt. However, after running it again, I encountered an error of not being able to connect to the model. I don't understand what is happening.

**Comment by stassius** [comment]
Can you show me the config.ini file as well?

**Comment by aerovfx** [comment]
[Main]
url = http://127.0.0.1:7860
timeout = 1.2

[Authorization]
useauth = False
username = test
password = pass

**Comment by aerovfx** [comment]
Usually reinstalling will succeed the first time.
However I will try again.
Thank you very much for your enthusiasm
