### ISSUE TITLE
api runtime error

### ISSUE THREAD

**Issue by nuclearpolygon** [stassius/StableHoudini#5]
Tried out the last commit and got everything broken 
the webui spits these errors:
[traceback.log](https://github.com/stassius/StableHoudini/files/11334409/traceback.log)
when I use webui directly it seems to be working

**Comment by stassius** [comment]
Do you mean the last commit of A1111 or the last commit of Stable Houdini? It looks strange. One user reported similar error and it was due to Python version incompatibility.

**Comment by mrmcdobrotny** [comment]
I mean this repo today's update. 
I have updated automatic yesterday, and everything was ok. I'll test it in another Linux environment and report any significant feedback

**Comment by mrmcdobrotny** [comment]
Btw my Houdini build runs python 3.9

**Comment by bobrity** [comment]
Hi! This is a problem with the API module of the Automatic 1111. I hope this will help you solve your problem. 

https://github.com/AUTOMATIC1111/stable-diffusion-webui/pull/9319

you need to apply the patch

4xmpl:

`git fetch origin pull/9319/head:test-branch
git checkout test-branch`

https://devopscube.com/checkout-git-pull-request/

У кого Линукс примените этот патч, проблема в API автоматика.

Потестить все доступные API вызовы можно тут. 
http://127.0.0.1:7860/docs

**Comment by nuclearpolygon** [comment]
@bobrity thanx a lot, this patch fixed the issue!
