### ISSUE TITLE
No license file

### ISSUE THREAD

**Issue by lgritz** [stassius/StableHoudini#6]
What is the license on the contents of this repo? Without a specific license posted, organizations that are trying to be legit in terms of compliance have to assume that they're not allowed to do anything with it, since that is the legal default in most countries.

**Comment by stassius** [comment]
Good point. I will add it later. Shortly put, you can use it in any way you want (except for the rick-roll sequence, obviously).

**Comment by stassius** [comment]
Added Apache 2.0 License.

**Comment by lgritz** [comment]
Thanks, great choice.
